title: Huong Tran
# logo: /assets/img/headshot_circle.png
description: I am a passionate graduate student in Computer Science & open to discuss about tech innovation, different data privacy methods and multimodal machine learning.
# show_downloads: true
theme: jekyll-theme-minimal
